export const THEME_GROUPS = [
  // ── 1. Trabajo ───────────────────────────────────────────────────────────────
  {
    id: 'trabajo', label: 'Trabajo', emoji: '💼',
    themes: [
      {
        id: 'stress-work', label: 'Estrés laboral',
        phrases: [
          'Welcome to this space of your own. For a few minutes, work and all its demands can wait. Bring your attention to your breath and allow yourself to be fully here.',
          'Feel the weight in your shoulders and gently allow them to release downward. With each exhale, let go of a little of that muscle tension. Your body knows how to release what it no longer needs to carry.',
          'Your mind worked hard today and deserves this genuine rest. Observe the thoughts that arise and let them pass without holding on to any of them. This is your recovery time.',
          'Each exhale carries away the tension accumulated in your body and mind. Imagine that with each breath your nervous system receives a signal of safety. Slowly, calm replaces activation.',
          'The pending tasks will still be there later, exactly where you left them. This moment is yours alone to recharge and regain clarity. Allow yourself to simply exist here without producing anything.',
          'You are far more than your productivity — your worth does not depend on how much you accomplish in a day. Take a deep breath and let that truth settle into your body. You are enough beyond what you achieve.',
          'Imagine the pressure of work dissolving with each breath you take. Visualize that tension leaving your shoulders, your jaw, your chest. The space that remains is yours to fill with calm.',
          'Your body knows how to recover — it only needs permission to do so right now. Give yourself that permission without conditions or guilt. This pause is not weakness; it is intelligence and self-care.',
          'The problems at work have solutions, and so does your inner peace. From a calm state, answers arrive with more clarity and less effort. Breathe and trust that process.',
          'Observe work thoughts like clouds passing without stopping in the sky. You do not have to follow them or resolve them right now. Your only task here is to breathe and let go.',
          'With each deep breath, your mental clarity is restored and your perspective expands. Rest does not paralyze your effectiveness — it powers and multiplies it. You are investing in your best self.',
          'When this session ends, you will return to work renewed, with greater focus and fresh perspective. Trust that this pause has a real purpose. What awaits you when you leave is worth waiting a few minutes.',
        ],
      },
      {
        id: 'focus-work', label: 'Enfoque y productividad',
        phrases: [
          'Center your attention on this present moment. Everything else — pending tasks, notifications, noise — can wait a few minutes. This is your time to prepare your mind.',
          'Feel how your mind settles and becomes clearer with each breath. Like water that stops being agitated, your clarity emerges on its own when given space. Watch it appear.',
          'Visualize your most important task with all its details and its final result. You see it completed successfully, exactly as you want it to look. Feel the satisfaction of that achievement in your body right now.',
          'Your best work always comes from a calm and focused mental state, never from tension. Pressure does not produce quality — calm does. This pause is an active part of your performance.',
          'Release the thoughts that scatter your energy right now. With each exhale, gently return to your center. Your focus sharpens when you stop forcing it.',
          'The clarity you need is already within you — it only needs space to fully emerge. You do not have to generate it; you just have to stop blocking it. Breathe and allow it to appear.',
          'With each exhale you release accumulated distraction. With each inhale you receive renewed and clean focus. This cycle is your most powerful tool before working deeply.',
          'Your mind is a precise instrument and this pause sharpens it for what comes next. Like a musician who tunes before playing, you tune your attention before creating. The quality of your work starts here.',
          'Visualize the flow of work you want to have today: calm, effective, and with natural momentum. Feel how your energy organizes itself toward that state. You are creating the inner conditions to achieve it.',
          'Deep concentration arrives when the mind is at rest, not when it is in forced tension. You cannot demand focus — you can create the conditions for it to arrive on its own. That is exactly what you are doing now.',
          'When you finish this session, you will carry this calm into everything you do throughout the rest of the day. Every task, every decision will be better from this inner state. This investment of time is already generating returns.',
          'You are ready to give your best today. Your mind and body are aligned, prepared, and at peace. When you leave here, act from that certainty without doubt.',
        ],
      },
      {
        id: 'event-work', label: 'Presentación o reunión',
        phrases: [
          'Take this moment to center yourself deeply before what lies ahead. Feel your feet on the ground and your breath as a firm anchor. Everything you need for this moment you already have within you.',
          'The nerves you feel are energy you can direct completely in your favor. They signal that you care about what you do, that you give your best. Breathe and transform that energy into full presence.',
          'You have prepared this with care and real dedication. Trust what you know, what you have practiced, and who you are as a person. Your preparation is done — now you just have to be yourself.',
          'Visualize yourself in the meeting: calm, clear, present, and connected with the people listening. Imagine your voice confident and your ideas well articulated. That image is already planting the state you want to have.',
          'Your voice is confident and your ideas have real, concrete value. You deserve to be heard with attention and genuine respect. Breathe into that conviction and let it settle in your body before you walk in.',
          'With each deep breath, your nervous system receives the signal that you are safe and prepared. Cortisol decreases, your voice stabilizes, your mind clears. You are recovering your best natural state.',
          'Think of other times you came through challenging or uncomfortable situations. That capacity has not left you — it is still exactly where it always was. You carry that complete track record with you into this presentation.',
          'You do not need to be perfect to have real impact — you just need to be authentic and prepared. People connect with authenticity far more than with any forced perfection. Be yourself and trust that fully.',
          'Success does not require the absence of nerves — it requires knowing how to breathe through them with calm and confidence. The best communicators feel nerves and use them as fuel. You are doing exactly that right now.',
          'Imagine everything going well: fluid, natural, with good connection and clear messages. Feel that genuine satisfaction settle into your body as a real and present sensation. That image is more powerful than you imagine.',
          'You are more ready than you think right now. Your preparation, your experience, and your clear intention support you completely. Trust the process and yourself without reservation.',
          'When you open your eyes, you will carry this calm and this confidence into every moment of the meeting. You can return to this state with a single conscious breath if you need it. You already know how.',
        ],
      },
      {
        id: 'impostor-syndrome', label: 'Síndrome del impostor',
        phrases: [
          'The feeling of not deserving your place is one of the most common experiences among highly capable people. You are not alone in this, and its presence does not make it true.',
          'Breathe deeply and let the armor of that impostor feeling soften a little. Beneath it is a real and capable person — the one who actually achieved what you fear you did not.',
          'The accomplishments you have made are real. They did not happen to you by accident or mistake. They happened because of choices, effort, and ability you genuinely have.',
          'The people around you see something real in you that you have difficulty seeing yourself. Their trust is not naive. Consider, carefully, that they might be right about you.',
          'Competence and confidence do not always travel together at the same speed. You can be highly capable and still feel like you are not. That gap is normal — not evidence of fraud.',
          'Let go for a moment of the constant internal comparison with an ideal version of yourself that does not exist. You are measuring yourself against a fiction. Come back to what is real.',
          'Every expert, every leader, every person you admire has felt this same doubt at some point. It is a companion of growth, not a sign that you do not belong. It means you care deeply.',
          'Your voice and perspective have genuine value precisely because they come from you — from your unique experience and way of seeing. No one else can contribute exactly what you can.',
          'Instead of asking whether you deserve to be here, ask what you can contribute from here. That shift from scarcity to purpose changes everything. You have something real to offer.',
          'The fear of being discovered does not reflect reality — it reflects how much you have invested in what you do. That investment is not weakness. It is the mark of someone who takes their work seriously.',
          'You are allowed to grow into new roles and challenges without having all the answers from the start. That is what growth actually looks like from the inside. Trust that process.',
          'When you leave here, carry one concrete truth: you have earned your place. Not because you are perfect, but because you have done real work and brought real value. That is enough — and it is real.',
        ],
      },
      {
        id: 'burnout', label: 'Agotamiento laboral',
        phrases: [
          'You have been running for a long time and your body and mind are asking — clearly and urgently — for a real stop. This is not weakness. This is the cost of a long and sustained effort.',
          'Burnout is not a character flaw or a sign that you are not strong enough. It is what happens when extraordinary demands go unmet for too long. It is a signal, not a verdict.',
          'Allow yourself to do nothing in this moment. Not rest as preparation for producing more — just rest because you need it and you deserve it. Full stop, with no other purpose.',
          'The things that feel urgent right now will not disappear if you rest for a while. But you might disappear — gradually and silently — if you do not. Rest is not optional when you are here.',
          'Your worth as a person is not measured by how much you produce or how available you are. You were valuable before you were busy. That original value is still fully there.',
          'With each deep breath, give your exhausted nervous system the signal it has been waiting for — that it can finally stop bracing for impact. Safety. Recovery. Rest. You are here.',
          'Think about what you used to enjoy before everything became work and obligation. That capacity for joy has not vanished. It is waiting quietly beneath the exhaustion. It will return.',
          'Sustainable performance always requires genuine recovery. The best athletes and thinkers build real rest into their lives not because they are weak, but because they are serious about their work.',
          'Something important needs to change beyond this session — a habit, a boundary, an expectation. This breath gives you a first moment of clarity about what that might be.',
          'Letting go of some things is not failure. It is the kind of wisdom that only comes from having pushed too far and learned what that cost. You are learning something real and valuable here.',
          'You are allowed to say that it has been too much. To yourself first, and perhaps then to others. That honesty is not complaint — it is self-knowledge. And it is the beginning of recovery.',
          'When you leave here, carry this: you are a whole person, not a function. Recovery is now part of your most important work. Begin it here, in this breath, and continue it beyond.',
        ],
      },
    ],
  },

  // ── 2. Relaciones ────────────────────────────────────────────────────────────
  {
    id: 'relaciones', label: 'Relaciones', emoji: '❤️',
    themes: [
      {
        id: 'conflict', label: 'Conflicto con alguien',
        phrases: [
          'This is your safe space to process what you feel, completely without judgment. Here you can feel everything you need to feel without having to act on it. Give yourself that permission now.',
          'It is completely valid to feel affected by a conflict — that makes you deeply human. You do not have to minimize what you feel in order to move on faster. Breathe and let the emotions exist.',
          'Inhale deeply and give real space for emotions to settle calmly. Like sediment in agitated water, they clarify on their own when you stop stirring them. Your clarity is arriving.',
          'Behind every conflict are unexpressed needs that deserve to be heard. Yours matter as much as the other person\'s. Calmly identify what you truly need.',
          'You do not have to resolve everything now or have immediate answers. You just need to be well yourself first, before anything else. That is not selfishness — it is wisdom.',
          'Bring your attention to your body. Where do you hold the tension of this conflict — your chest, your jaw, your stomach? Breathe gently toward that place with each inhale and release it with each exhale.',
          'True understanding arrives when the mind is calm, not when it is reactive and defensive. From this state of calm, you will see options that were not visible before. Wait for that moment.',
          'You can feel hurt and also consciously choose how you want to respond. That choice is your greatest power in any conflict. Breathe and decide from there, not from the pain.',
          'Let go for now of the urgent need to be right or to resolve everything. Find your inner peace first and clarity will come afterward naturally. The conflict does not disappear, but you face it differently.',
          'With each breath, you create healthy distance between the event and your emotional reaction. That distance is not coldness — it is wisdom and real self-control. From there you can act with more integrity.',
          'Genuine relationships survive conflicts when there is willingness and clarity from both sides. This moment of pause is already an act of care toward the relationship. You are choosing well.',
          'When you leave here, you will have greater clarity, calm, and perspective to face this situation. You will carry not only calm, but also a broader understanding. That is the gift of this pause.',
        ],
      },
      {
        id: 'social-anxiety', label: 'Ansiedad social',
        phrases: [
          'This space is completely yours. Here there is nothing to prove, no one to judge you, no expectation to meet. Just you and your breath.',
          'Social anxiety is an automatic bodily response to a perceived threat, not a truth about who you are. Your body is trying to protect you with excessive zeal. You can thank it and relax it.',
          'Breathe slowly and deeply. Your nervous system is receiving the signal that you are safe right now. Each calm breath teaches your body that it can relax.',
          'You do not have to be liked by everyone or approved of by every person you meet. You just have to be honestly yourself and the right connections will come. That is enough.',
          'Others are much more focused on their own thoughts than you imagine. The attention you feel on yourself exists mainly in your mind. Breathe and release that imaginary burden.',
          'With each breath, you reduce the alarm signal in your central nervous system. Cortisol drops, muscles relax, the mind calms. You are training your body toward peace.',
          'Think of someone with whom you feel completely comfortable and accepted as you are. Feel that warmth in your body for a moment. That same peace is available in many more contexts than you believe.',
          'You have perspectives, ideas, and something valuable to offer the world around you. Your authentic presence truly matters. You do not have to be perfect to deserve space and to be heard.',
          'The social discomfort you feel is a temporary and passing sensation, not a life sentence. This session is helping you move through it with more resources. Each time you do, you become more capable.',
          'Your words have real value. Your unique perspective deserves to be shared without apology. Practice believing that here in the safety of this space before carrying it into the world.',
          'With consistent practice and genuine patience with yourself, social anxiety yields ground little by little. You do not have to resolve it all today. Each conscious breath is already a meaningful step.',
          'When you finish, you will carry a calmer, more grounded, and more confident presence into the world. You will notice small differences. Trust the process and your own progress.',
        ],
      },
      {
        id: 'loneliness', label: 'Soledad',
        phrases: [
          'Being alone does not mean being abandoned or unloved. You are valuable company for yourself. Learn to inhabit that space with gentleness.',
          'Breathe deeply and feel your own heart beating strongly. There is life, warmth, and genuine presence in you. You are never completely alone as long as you are with yourself.',
          'The loneliness you sometimes feel is just the natural space between human connections. It is temporary and known by everyone. It will pass, as it always has.',
          'Give yourself the same gentleness, patience, and care you would unhesitatingly give to a friend who feels lonely. You are just as deserving of that compassion as anyone else. Start with yourself.',
          'Think of a specific person who appreciates and loves you, even if they are far away right now. Feel that real affection as warmth in your chest. That love exists even when you cannot see it in this moment.',
          'Genuine connection can bridge physical distance and time. There are people who think of you even if they do not say it right now. That too is real and present.',
          'Use this stillness as a valuable gift that few allow themselves. There is something in you that only blooms in silence and solitude. Discover it with curiosity and without fear.',
          'Solitude can be a profound invitation to know yourself more genuinely. What do you discover when the external noise fades? Listen to what emerges in this inner space.',
          'Remember specific moments of genuine connection you have lived with people who matter to you. Those moments shaped you and still inhabit you. You carry that richness with you always.',
          'Your presence in the world makes a real difference, even if you do not always perceive it. The people who know you are better for having found you. That is true.',
          'Every time you care for yourself with love and attention, you build the best possible company. You become someone who enjoys your own presence. That changes everything.',
          'You deserve deep connection and you will find it when the moment is right. For now, this inner calm is also a valid and real home. Inhabit it with peace.',
        ],
      },
      {
        id: 'couple-conflict', label: 'Discusión de pareja',
        phrases: [
          'Take this necessary space for yourself before continuing the conversation. It is not running away — it is preparing yourself to speak better. This pause is already an act of care toward the relationship.',
          'What you feel has complete validity and deserves to be recognized. And what the other person feels also has its own validity. Two truths can coexist without either negating the other.',
          'Breathe deeply and let reactivity dissolve gently before responding. Words spoken in calm are always more effective and less harmful. Wait for that moment.',
          'A conflict does not define the relationship or its future. It defines how you choose to move through it together and what you learn. This is one of those defining moments.',
          'What do you truly need from this situation — beyond winning or being right? Ask yourself honestly and without judgment. That clarity is the starting point for a real conversation.',
          'With each breath, you create valuable space between the pain you feel and your response. That space is where your best decisions live. Protect it and expand it with each inhale.',
          'Words and actions that come from calm have far more transformative power than those that come from anger. This is not giving in — it is choosing to be more effective. Breathe into that conviction.',
          'Think about what you genuinely value in this person and in this relationship. That love is also real and present, even if it is now covered by conflict. It has not disappeared.',
          'Honest vulnerability often resolves far more than winning any argument. Saying it hurt me or I need this has more power than arguing about who is right. That requires courage.',
          'You do not have to have everything clear or resolved right now. This pause is already an important step forward. When you feel calmer, the right words will come more naturally.',
          'From this calm and grounded state, you can listen with more openness and be heard better. Real communication only happens when both people are present and receptive. You are preparing yourself for that.',
          'When you leave here, carry the genuine intention to understand before seeking to be understood. That attitude completely changes the dynamic of any difficult conversation. It is a gift you give yourself and the relationship.',
        ],
      },
      {
        id: 'family-tension', label: 'Tensión familiar',
        phrases: [
          'Families are complex, contradictory, and also profoundly beautiful. This moment is to find your center before returning to that world. Breathe and anchor your identity.',
          'Breathe and clearly separate what you can control from what is beyond your reach. Focus your energy only on the former. Letting go of the latter is not surrender — it is wisdom.',
          'You do not have to resolve the entire family dynamic today or carry the weight of every problem. You just need to be well yourself as the condition for anything else. That is enough.',
          'The family burden is real and can be very heavy at certain moments. But not all of it belongs to you to carry alone. Learn to distinguish what is your part and what is not.',
          'Each breath returns you to yourself, outside the roles and expectations you play in family. For a moment, you are just yourself without any title. Feel that genuine freedom.',
          'Think of a specific moment of genuine love and real connection with your family. That also exists and is as real as the tension. Both coexist in the same story.',
          'You can love your family deeply and also set healthy and necessary boundaries. They are not opposites — they complement each other. Healthy boundaries are a form of love, not a betrayal.',
          'The strongest tree has deep roots that sustain it without limiting it. Your family roots give you context and strength, not just restrictions. You can honor them and also grow beyond them.',
          'With each exhale, you consciously release the expectations that belong to others, not to you. You do not have to meet them all to be enough. Choose what to carry and what to release with freedom.',
          'Your personal well-being is also a real gift to your family, even if they do not always see or acknowledge it. When you are well, you have more to give. Taking care of yourself is also caring for them.',
          'From this state of calm and integrity, your words will have more positive and lasting impact. Difficult conversations resolve better from here. It is worth arriving at that state.',
          'You carry love within you that is greater than any tension you are living through right now. That love survives the difficult moments. Trust it as the foundation of everything that comes.',
        ],
      },
    ],
  },

  // ── 3. Situaciones ───────────────────────────────────────────────────────────
  {
    id: 'situaciones', label: 'Situaciones', emoji: '🌆',
    themes: [
      {
        id: 'traffic', label: 'Estrés en el tráfico',
        phrases: [
          'Traffic is outside of you and beyond your control. This inner space is completely yours and no one can take it from you. Breathe and remember that.',
          'You cannot control traffic or when it will move. But you can choose how you breathe and what you feel in this moment. That choice is all the power you need.',
          'Consciously release your jaw, your shoulders, and the hands gripping the wheel. Feel that tension yield simply by noticing it. Breathe toward those places.',
          'Each pause in traffic is actually an invitation to take a deep, conscious breath. You are turning lost time into recovery time. That changes everything.',
          'The destination will arrive exactly when it is meant to. The journey does not have to be unnecessary suffering. Choose how you want to live it.',
          'Your time is not lost in traffic — that is inevitable. Your peace, however, is only lost if you choose to give it away. Reclaim it with each conscious breath.',
          'Breathe deeply and remember that this, like everything in life, is completely temporary. This moment of traffic will pass. What you build within yourself while waiting, remains.',
          'Every meter you advance is one real meter closer to where you are going. There is progress, even if it is slow and irregular. Your direction has not changed.',
          'With each slow, deep breath, you reduce cortisol in your blood and tension in your muscles. Your body responds immediately to this care. You are taking care of yourself while you wait.',
          'Think of something concrete and good that awaits you when you arrive — a person, a meal, your own space. Feel that something like a magnet drawing you calmly forward. It is coming.',
          'You are larger and more capable than this moment of impatience and discomfort. Your calm is a real choice you can make right now. That is your victory.',
          'You will arrive — that is inevitable. And when you do, you can arrive in peace if you choose to breathe now instead of tensing up. You will feel that difference when you step out of the car.',
        ],
      },
      {
        id: 'transition', label: 'Entre actividades',
        phrases: [
          'You finished one thing and are moving toward another. This space between them is your moment of conscious transition. Use it with intention.',
          'Let go of what came before before you arrive mentally at what comes next. You do not have to carry the energy of one activity into the next. You can choose to arrive clean.',
          'Your mind still carries the energy residue of what just happened — thoughts, emotions, tensions. This breath helps you release them completely. You are doing a reset.',
          'With each exhale you intentionally release what has passed. With each inhale you receive openness and freshness for what comes. This is the cycle of a conscious life.',
          'You do not have to arrive at the next place or the next person carrying all the weight of what just happened. You can choose to begin each thing anew, from zero. That choice is yours.',
          'This pause between activities is not lost time. It makes you more effective, more present, and calmer in what follows. It is an investment that generates immediate return.',
          'Imagine your mind is a whiteboard. Each deep breath clears it a little more. When this session ends, it will be ready to receive the new with clarity.',
          'You arrive wherever you are going as the best version of yourself available. That is the only responsibility you have in each transition. Bring yourself, in calm.',
          'The best transitions are the ones done consciously, with intention and presence. You have that opportunity right now. Do not let it pass.',
          'Your full presence in what comes next is the greatest gift you can give that next activity and the people waiting for you. This pause makes it possible.',
          'Release the past with real gratitude for what it was. Receive the present with genuine openness. That is the practice of living well.',
          'You are ready for what comes. This pause was the bridge between what was and what will be. You crossed it well.',
        ],
      },
      {
        id: 'arriving-home', label: 'Llegada a casa',
        phrases: [
          'You made it home. The outside day and everything it brought can stay outside tonight. Something different begins here.',
          'This space is your home and it deserves your full presence, not just your exhausted body. Allow yourself to truly enter it, in every sense.',
          'Feel how your body instinctively recognizes the safety and familiar feeling of being home. That relaxation emerging — give it permission to expand.',
          'With each breath, you gradually release work mode and its tensions. And you gradually recover life mode and its textures. It is a shift you can make consciously.',
          'The people waiting for you deserve your real presence, not just your body present in the space. This pause is the gift you give them before you walk in. And that you give yourself.',
          'Before crossing the door, make this transition from the inside where it truly matters. One minute here can completely change how the evening at home unfolds. It is worth the time.',
          'The stress of the day does not have to come in with you or infect your space. It can stay symbolically at the threshold, outside. Decide that it will.',
          'Think of something small and specific that makes your home special and yours. A person, a corner, a smell, a routine. Smile inwardly toward that.',
          'With each exhale, you release the character you play at work and all its masks. And you recover who you are at home, with family. That person is also valid and deserves space.',
          'Your family, your space, your people — they are waiting for you. Arrive to them whole and present, not halfway. That is what they need most from you.',
          'The best thing you can bring home is not anything material — it is your calm, your presence, and your openness. That cannot be bought. It is cultivated, as you are doing now.',
          'Welcome back to yourself and to what matters most. The true home always begins within. You are already there.',
        ],
      },
      {
        id: 'big-decision', label: 'Antes de una decisión',
        phrases: [
          'You are facing a decision that matters to you, and that weight is real and legitimate. This session gives you a moment to step back before you step forward. That pause is wisdom.',
          'Begin by breathing slowly and creating space between you and the urgency. Most important decisions can wait the few minutes it takes to become clear. This is that time.',
          'Notice the noise of other people\'s opinions, fears about getting it wrong, and pressure to decide quickly. Now, gently set all of that aside. This moment belongs to your own inner knowing.',
          'Ask yourself what you truly want from this — underneath the fear of regret and the pressure to be right. That authentic preference is important data. Listen to it with respect.',
          'Your body often knows before your mind does. Where do you feel tension when you imagine one option versus the other? That physical response is intelligent feedback, not noise.',
          'Consider what you will think of this decision ten years from now. Not which option turns out perfectly, but which one aligns with who you are and what you value. That question clarifies.',
          'There is rarely a perfect decision waiting to be found. There is only the best decision you can make with the information and clarity you have right now. That is genuinely enough.',
          'Release the need to control how this turns out completely. Every decision opens some doors and closes others. That is not failure — it is the nature of choosing at all.',
          'Think of past moments when you made a difficult decision and moved forward. You survived that uncertainty and you learned from it. That same capacity is fully intact today.',
          'Trust yourself more than you trust your fear. Fear generates worst-case scenarios and calls them predictions. Your judgment, based on real values and real experience, is more reliable.',
          'Whatever you decide, you will handle what comes from it. You always have. The future version of you is capable of adapting to whatever this choice brings. Trust that version.',
          'When you leave here, you will carry more clarity, more calm, and more trust in yourself. The decision does not have to be made this instant. But now you are better prepared to make it well.',
        ],
      },
      {
        id: 'sunday-anxiety', label: 'Ansiedad del domingo',
        phrases: [
          'Sunday has a particular weight for many people — that mix of quiet and anticipation before a new week. If you feel it, you are not alone, and it has a name and it makes complete sense.',
          'Breathe and come back to this moment, this afternoon, this precise hour. The week has not started yet. You are still here, in this day, in this breath. Be here.',
          'That low-level anxiety about Monday is your mind rehearsing scenarios it cannot yet know. Thank it for trying to prepare you, and gently bring it back to now. The future is not yet real.',
          'What is actually good or comfortable about this moment right now, even if small? A warmth, a sound, a stillness, a person nearby. Locate something real and let it be enough for a moment.',
          'The week that is coming will unfold one hour at a time, one situation at a time. You will not face it all at once. You will face it sequentially — and you can handle each piece as it arrives.',
          'You have survived every Monday that has come before. Every difficult week has ended. The week ahead, whatever it holds, will also end. That is not hope — it is your confirmed history.',
          'With each slow exhale, release a little of the anticipatory weight you are carrying about something that has not yet happened. The present is yours. The future is not yet asking anything of you.',
          'Ask yourself honestly — is there something specific worrying you, or is it a general feeling of dread? If it is specific, it may be solvable. If it is general, it belongs to anxiety, not to reality.',
          'Think about what you are looking forward to this week, even one small thing. A conversation, a meal, a moment of accomplishment. That also exists alongside whatever you fear.',
          'Rest on Sundays is not a luxury or laziness. It is the legitimate infrastructure of a sustainable week. You are not failing by resting. You are doing exactly what a functioning human being needs.',
          'The version of you that will face Monday morning is not the version feeling this anxiety right now. After sleep, after rest, things genuinely look and feel different. That is biology, not delusion.',
          'When this session ends, come back to the rest of Sunday. Not to Monday yet. Enjoy, or at least inhabit, what remains of today. It is still yours and it is enough.',
        ],
      },
    ],
  },

  // ── 4. Emociones ─────────────────────────────────────────────────────────────
  {
    id: 'emociones', label: 'Emociones', emoji: '🌊',
    themes: [
      {
        id: 'sadness', label: 'Tristeza',
        phrases: [
          'It is completely valid to feel sadness and you do not have to fight against it or rush it. Let it be with you as a visitor, not an enemy. Breathing together already helps.',
          'Allow the sadness to be with you in this moment without settling in permanently or defining you. It can exist here and also pass. Both things are true.',
          'Breathe gently and give generous space to what you feel without labeling or judging it. Just observe with the same gentleness you would give to someone you love. That gentleness is for you too.',
          'Sadness is a sign that something or someone matters deeply to you. That is not weakness — it is deeply human and beautiful. Only those who love feel this.',
          'You are not broken. You are processing something difficult and that requires time and space. There is an enormous difference between being broken and being in the process of healing.',
          'With each deep breath, you generate a small space of relief within yourself. That space does not erase the sadness — it coexists with it. And in that space you can breathe.',
          'Feelings, even the heaviest and darkest ones, are temporary and passing. No emotion lasts forever, even if it seems that way in the moment. This one will pass too.',
          'Give yourself the same real compassion you would give without thinking to a friend going through the same thing. Without conditions, without rush, without judgment. That is what you deserve right now.',
          'There is light in you even when you cannot feel it or see it. What you feel right now is not all that you are, nor does it define what you will be. It is a passing moment in a much larger story.',
          'You do not have to understand why you feel this way or find the logical cause. You just have to move through it with gentleness and presence. Understanding will come later, on its own.',
          'Each deep breath activates your parasympathetic nervous system — the one that calms and heals. Your body is already responding and helping. Trust that natural process.',
          'When you finish, you will carry a little more lightness with you. The sadness will gradually yield space. Not all of it today, but something. And that counts.',
        ],
      },
      {
        id: 'anger', label: 'Ira o frustración',
        phrases: [
          'You are feeling something very intense right now and that is okay. This space is completely safe for you and for what you feel. You do not have to control it right now.',
          'Anger is powerful energy. Now we direct it inward to understand it, not outward to destroy. That redirection is your strength.',
          'Breathe deeply and slowly, slower than normal. Your nervous system needs this clear signal of calm to exit alarm mode. Each breath counts.',
          'Behind every genuine anger there is an unmet need that is calling out to be addressed. What is yours right now? Identify it honestly and without judging yourself.',
          'You can feel anger fully without it controlling or defining you. Feeling is not acting. You can be furious and still choose how to respond. That is your freedom.',
          'With each exhale, you release accumulated pressure like a valve that opens gently and with control. It is not an explosion — it is conscious and gradual release. Your pace.',
          'The response that emerges from calm has infinitely more transformative power than the one born from rage. This is not giving in — it is becoming more effective. Wait for that state.',
          'Observe the anger without identifying with it. You are the observer of that emotion, not the emotion itself. From that perspective you have much more power and clarity.',
          'When anger passes, something softer usually remains beneath it — pain, fear, frustration. Allow that softer thing to emerge. That is where the real answers are.',
          'Your well-being and inner peace are more valuable than winning any argument or being right. That clarity of priorities is wisdom in action. Breathe into it.',
          'Each deep breath reduces active cortisol in your blood and tension in your muscles. Your body is already healing and regulating itself. Help it with one more breath.',
          'When you leave here, you will be able to respond from clarity instead of reacting from pain. That difference completely changes the outcome. Every second of this pause is worth it.',
        ],
      },
      {
        id: 'fear', label: 'Miedo o incertidumbre',
        phrases: [
          'The fear you feel is real and has reason to exist. So is your capacity to move through it without it destroying you. Both things are true at the same time.',
          'Breathe and anchor your full attention in this present moment. Here, right now, you are safe. Fear lives in the future — you live in this instant.',
          'You cannot control how the uncertain future will unfold. But you can be well in this precise instant. That is all that is asked of you right now.',
          'Your mind is generating possible and probable scenarios. Gently bring your attention back to your breath. It is your anchor to the only moment that exists: this one.',
          'You have moved through difficult and uncertain moments before and you came through. You carry that learning and that capacity with you now. Your track record speaks for you.',
          'Uncertainty is a permanent condition of human life, not an error or a failure. Your capacity to adapt and move forward is too. They are companions.',
          'With each slow, deep breath, you activate your parasympathetic nervous system — the system of calm. Your body responds immediately. You are changing your physiological state.',
          'You do not need to know how everything will turn out in order to be well in this moment. Peace does not depend on certainty. It can exist within uncertainty.',
          'Fear of the future exists in your mind as an imagined scenario. Your body, however, only exists in this present moment. Return to it with your breath.',
          'Trust the future version of yourself that will already know what to do with whatever comes. That version exists and is being formed by how you move through this moment. You are growing.',
          'You are more resilient than you believe in this moment of fear. Your story proves it on every page. Trust that concrete evidence.',
          'When you leave here, you will carry more calm, more confidence, and more faith in your ability to move forward. Not certainty about the outcome, but trust in yourself. That is more valuable.',
        ],
      },
      {
        id: 'anxiety-worry', label: 'Ansiedad y preocupación',
        phrases: [
          'Anxiety is one of the most common human experiences and one of the least talked about. You are not broken, unusual, or weak. You are a person dealing with something very real.',
          'Breathe slowly — slower than feels natural right now. Your nervous system responds to your breath rate. A slow exhale directly activates the calming branch of your nervous system. Use it.',
          'Notice where anxiety lives in your body right now. Chest tightness, a racing heart, a tight stomach. Those sensations are real, but they are not dangerous. They are your body responding to perceived threat.',
          'The anxious mind tends to see threats as certain and catastrophic. Gently ask: is this happening right now? Is it actually as certain and permanent as it feels? Often, the honest answer is no.',
          'You do not have to eliminate anxiety to live well with it. You can breathe alongside it, move alongside it, and choose alongside it. It does not have to stop you.',
          'Worry is the mind trying to feel in control by rehearsing scenarios. It feels like preparation but usually adds suffering without adding solutions. Breathe and notice that distinction.',
          'With each exhale, you reduce the cortisol driving this state. With each slow inhale, you signal to your body that it is not under attack. This practice has measurable physical effects.',
          'What is the most likely outcome of what you are worrying about — not the worst case, but the realistic one? Often it is manageable, even if uncomfortable. Return to the probable, not the catastrophic.',
          'This moment is survivable. The anxiety is intense but it is not permanent or physically dangerous. You have felt this before and moved through it. That is your record. Trust it.',
          'You are bigger than your anxiety. It is a part of your experience — it is not the whole of who you are. From this breath, look at it as the observer, not as the experience itself.',
          'Self-compassion — treating yourself with the same gentleness you would offer a friend who is struggling — is one of the most effective responses to anxiety. Give that to yourself now.',
          'When you leave here, carry one thing: anxiety passes. It always has. This state is temporary, even if it does not feel that way. You have moved through it before and you will again.',
        ],
      },
      {
        id: 'self-criticism', label: 'Autocrítica y autoestima',
        phrases: [
          'The inner critic is often the loudest voice in the room. It speaks with such confidence. But confidence does not equal truth, and harshness does not equal wisdom. You are allowed to question it.',
          'Breathe and create a small space between you and that critical inner voice. You are not the voice — you are the one hearing it. That difference matters more than it might seem right now.',
          'Ask yourself honestly: would you speak to a close friend the way you speak to yourself? If the answer is no, then something important is out of alignment. You deserve the same kindness you give others.',
          'High standards and harsh self-criticism are not the same thing. One helps you grow. The other simply erodes the foundation you need to grow from. One serves you. The other does not.',
          'Behind every persistent self-criticism there is usually a genuine need — to be accepted, to be good enough, to be loved. What are you actually longing for beneath the criticism? Listen to that.',
          'You have done things right, genuinely and concretely. Name one specific thing. Let it be real and let it be enough for this moment. The mind that only notices failures is not being accurate.',
          'Your mistakes do not define your worth. They are data — useful, sometimes painful, but nothing more permanent than data. You are allowed to learn and to remain whole at the same time.',
          'With each breath, practice offering yourself the benefit of the doubt — the same benefit you would generously give to someone you care about. You are a work in progress. So is everyone.',
          'Perfectionism often comes from a belief that being imperfect means being unlovable. That belief is not true, but it runs deep. Breathe toward the possibility that you are enough right now, as you are.',
          'You are worthy of care and belonging, not because you perform perfectly, but because you exist. That is the foundation of self-worth that no achievement can give and no failure can take away.',
          'Real self-improvement comes from self-understanding, not self-punishment. The kinder and more honest voice is also the more effective one. Try that voice with yourself today.',
          'When you finish, carry a small, concrete commitment to speak to yourself a little more kindly today. Not perfectly — just slightly more gently. That shift, practiced daily, changes everything.',
        ],
      },
      {
        id: 'grief', label: 'Duelo o pérdida',
        phrases: [
          'Grief is love with nowhere to go. What you feel is a direct measure of how much something or someone mattered to you. That matters, and so does this pain.',
          'There is no correct way to grieve and no timeline you are supposed to follow. What you feel is valid, even if it changes hour to hour or contradicts itself. All of it is allowed.',
          'Breathe gently and allow yourself to feel without rushing toward any resolution. Grief is not a problem to be solved. It is a process to be moved through, at your own pace, in your own way.',
          'Your loss is real. The absence left by something or someone who mattered is real. You do not have to minimize it or explain it or have it make sense right now.',
          'Even in the deepest grief, the breath continues. Life insists on continuing through you, even when you are not sure you want it to. There is something quietly important in that persistence.',
          'With each exhale, release a little of the tightness you carry around this loss. You do not have to let go of the love — only the grip of acute pain. They are different things.',
          'You are allowed to have moments of peace without feeling that you are forgetting or betraying what you lost. Joy and grief can coexist. Relief is not disloyalty.',
          'Think of one specific thing you are grateful to have had — the experience, the relationship, the time. Even brief or imperfect gifts leave something real behind. That something is still with you.',
          'Grief comes in waves. When the wave is strong, breathe through it. When the water pulls back, rest in the space between. Both the wave and the calm are part of the same process.',
          'Healing does not mean the pain disappears completely. It means you find a way to carry it that allows you to live alongside it. That is not giving up. That is adapting with love.',
          'You do not have to have arrived anywhere by now. Grief does not follow a schedule and it does not respect expectations. The only measure that matters is how you are treating yourself in it.',
          'When you leave here, carry a little more gentleness with yourself. Grief is one of the heaviest things a person can carry. You deserve real care as you carry it. You are doing the best you can.',
        ],
      },
      {
        id: 'guilt-shame', label: 'Culpa o vergüenza',
        phrases: [
          'Guilt and shame live in the body as well as the mind — in the chest, the stomach, the skin. Breathe toward where you feel it. Bringing awareness there is the first step through it.',
          'Guilt says: I did something wrong. Shame says: I am something wrong. It helps to know which one you are carrying. One points to an action. The other points to your worth — and your worth is not negotiable.',
          'The fact that you feel guilt or remorse is evidence of your conscience working — of the fact that you have values and care about them. That capacity for conscience is not a flaw. It is something real and good.',
          'You are human. Humans make mistakes, say things they wish they had not, and hurt people they love. That is not a disqualifying fact. It is the basic condition of being alive and in relationship.',
          'If there is something real to address — a repair to make, an honest conversation to have, an apology to offer — breathe toward the clarity to do that. Action can transform guilt. Rumination cannot.',
          'With each deep exhale, see if you can release a fraction of the self-judgment you are carrying. Not the accountability — just the punishment. You are allowed to acknowledge wrongdoing without erasing your own worth.',
          'You did not act from your best self in that moment. That is a fact. But it is not the only fact about you — not even close. People are more than their worst moments. So are you.',
          'Shame thrives in silence and isolation. Simply naming what you feel here — even only to yourself — begins to reduce its power. Bringing it to the surface, into the light, already changes it.',
          'Forgiveness — of yourself or others — is not saying that what happened was acceptable. It is freeing yourself from the ongoing damage of carrying it. It is a gift to yourself, not an excuse.',
          'You can hold yourself accountable and also hold yourself with compassion at the same time. Those two things are not opposites. Together, they are how people actually grow.',
          'You are more than this moment, this mistake, or this feeling. The story you are living is long and complex and has many chapters. This is not the whole book — it is one page in a much larger story.',
          'When you finish, carry the intention to make what repairs you can — and then to allow yourself to move forward. Staying in guilt forever serves no one, including those you may have hurt. You deserve to live beyond it.',
        ],
      },
    ],
  },

  // ── 5. Descanso ──────────────────────────────────────────────────────────────
  {
    id: 'descanso', label: 'Descanso', emoji: '🌙',
    themes: [
      {
        id: 'morning', label: 'Inicio del día',
        phrases: [
          'Good morning. This is the first moment of a new day that is entirely yours. Before the world asks anything of you, this space belongs to you.',
          'Before the world calls on you and the schedule begins, take this real time for yourself. It is the most important gift you can give yourself each morning. Begin from within.',
          'Feel how your body awakens gradually with each conscious breath you take. Muscles lengthen, the mind clarifies, energy emerges. Observe that process.',
          'Today is a real and complete new opportunity. What happened yesterday stayed in the past where it belongs. You have a new page waiting.',
          'How do you want to feel today? Establish that clear and specific intention now. Not what you have to do — how you want to be while doing it.',
          'Your body and mind are preparing together for the day. Help them with calm, with presence, and with gratitude. This preparation makes a difference.',
          'Think of one small, concrete thing you want to genuinely enjoy today. A coffee, a conversation, a moment of sunlight. That is also the day.',
          'You do not need to have everything planned or controlled to begin with strength. You just need to begin with presence and intention. The rest will order itself.',
          'This moment of stillness at the start of the day is a powerful gift you are giving yourself. Conscious mornings change the day. You are doing something real.',
          'You carry with you everything you need for the day that begins. The ability, the experience, the intention. It is more than you think.',
          'Breathe deeply and fill your body with the quiet, focused energy you need. Every cell receives that oxygen. Your day starts from the inside out.',
          'Welcome to your day. Begin from the inside out, from calm toward action. From this moment of stillness toward everything that comes.',
        ],
      },
      {
        id: 'evening', label: 'Cierre del día',
        phrases: [
          'The day is ending and it is time to consciously release everything it was. The good that was, with gratitude. The difficult that was, with gentleness. Both deserve that closure.',
          'Review the day mentally without judging or grading it. Just observe what happened as a compassionate witness. There is no grade to give — there is releasing to do.',
          'What went well today, large or small? Give it the genuine recognition it deserves before letting it go. Acknowledging the good is not vanity — it is honesty.',
          'What was difficult or painful today? Release it with gentleness and without drama. You did what you could with the resources you had. That was enough.',
          'Your body carried many things today — physical, emotional, mental. Thank it for everything it held without complaining. And allow it to truly rest now.',
          'With each exhale, you consciously deposit the weight of the day somewhere that is not your body. Tomorrow you can pick it up if you need it. Tonight, rest.',
          'Tomorrow there will be another opportunity for what remained unfinished or unresolved. Tonight is for resting, not for resolving. Set limits on your work thoughts.',
          'Remember someone who brightened your day today, even with something small. A smile, a word, a gesture. That moment also existed and deserves recognition.',
          'You are safe in this moment. The day is over and there is nothing more to resolve right now. You can release constant vigilance and truly rest.',
          'Your mind deserves to rest as much as your body after a long day. Let go of the pending items until tomorrow, when you will be more rested. You do not resolve them now anyway.',
          'What was not resolved today can patiently wait until tomorrow when you have more energy. You cannot wait for the rest your body needs. Prioritize well.',
          'Close this day with genuine gratitude for what it was. You did what you could with what you had. It was enough. That is always enough.',
        ],
      },
      {
        id: 'gratitude', label: 'Gratitud',
        phrases: [
          'Stop for a real moment and observe what you have with clarity, not what you lack. The balance between both gives you perspective. Begin with what is here.',
          'Think of a specific person who brought light, warmth, or joy to your life today, even with something small. Feel gratitude for their existence in your story.',
          'Your body breathes, beats, and moves in this moment without you having to ask it to. That is an extraordinary and everyday gift that many cannot take for granted. Be grateful for it.',
          'There is something in your life that you take completely for granted and that someone else would wish to have. What is it? Name it internally and feel the real weight of that gift.',
          'Gratitude does not deny pain or erase what has been difficult. It just makes space for what is also good and true. Both can coexist honestly.',
          'With each inhale, you receive the gift of air, oxygen, and life. With each exhale, you give thanks and return it. It is the most basic and most sacred cycle.',
          'Think of something in nature that you genuinely like — the sun, the sky, rain, the wind. All of it exists and is freely available to you. Nothing charges you for it.',
          'There are people in your life who love you genuinely. Feel that real warmth in your chest for a moment, even if they are far away. That love exists right now.',
          'Gratitude transforms the ordinary into enough and the enough into abundance. It is one of the most powerful practices that exist for changing the perception of reality.',
          'When you leave here, carry this grateful gaze into the rest of the day and into the people you encounter. The world looks different from gratitude. Try it.',
          'Your story, with all its difficulties, scars, and mistakes, has formed you into who you are today. That too deserves genuine gratitude. Nothing was in vain.',
          'You are enough. You have enough. In this precise moment, there is peace available for you. Everything you need is here.',
        ],
      },
      {
        id: 'sleep-prep', label: 'Preparación para dormir',
        phrases: [
          'The day is behind you and belongs completely to the past now. What comes next is rest — real, restorative, necessary rest. Your only task from this moment is to allow it.',
          'Feel the support beneath your body — the mattress, the pillow, the warmth that surrounds you. You do not have to hold yourself up anymore. Surrender into that support fully.',
          'Your mind may still be moving through the events of the day. That is natural and expected. Let those thoughts drift by like leaves on a slow stream — noticed, not followed. Just breath.',
          'With each exhale, release the role, the obligations, and the identity of the active day. With each inhale, welcome stillness, darkness, and the quiet belonging of nighttime. You are transitioning now.',
          'There is nothing left to resolve or decide tonight. Every question that still feels open can wait until tomorrow without losing anything. Tonight, you just need to breathe and soften.',
          'Your body knows how to fall asleep — it has done it thousands of times without effort or instruction. You do not have to make it happen. You just have to stop preventing it by staying tense.',
          'Let your muscles release one by one, beginning with your face — your jaw, your forehead, the space around your eyes. Then your shoulders, your hands. Let weight sink downward with each breath.',
          'Imagine a place of complete safety and total rest. It might be real or entirely imagined. Let your mind move toward it slowly, with each breath, without forcing any detail.',
          'The events of tomorrow are not yet real and do not require your attention tonight. If your mind goes there, gently bring it back here — to the quiet, the dark, the slow breath. Stay present.',
          'You gave enough today. You were enough. There is no last thing you need to review or accomplish before sleep. That work is done. Let it stay done until morning.',
          'Notice how your breath slows naturally as your body prepares for sleep. Your nervous system is settling on its own. You are already moving in the right direction. Follow that movement.',
          'Sleep is one of the most profound forms of self-care that exists. By resting now, you are giving your body and mind exactly what they need to face tomorrow well. Let go. You are safe.',
        ],
      },
      {
        id: 'insomnia', label: 'Insomnio',
        phrases: [
          'You are awake when you did not want to be. That is frustrating, and your frustration about it is completely valid. Take a breath and begin here, in this exact moment, exactly as things are.',
          'One important thing first: fighting wakefulness creates more wakefulness. This session is not about forcing sleep — it is about releasing the fight. Let go of the struggle and something else becomes possible.',
          'Your body is resting even now, even while your mind is awake. Lying still in the dark is doing real work — recovering, regulating, restoring. It is not nothing. It is something.',
          'Breathe in slowly for four counts, hold gently for two, and exhale slowly for six. Do this just a few times. The extended exhale specifically activates your calming nervous system. Let it work.',
          'Instead of demanding sleep, invite rest. Not the same thing. Rest means allowing your body to be still, your thoughts to soften, your muscles to release. Sleep may follow. And if not, rest is still valuable.',
          'If thoughts are circling, acknowledge them briefly without following them. I hear you. Not now. Then return to your breath, to the dark, to the physical sensations of lying down. Return, each time, without frustration.',
          'Notice any tension in your body and consciously release it — your jaw, your hands, your belly. Tension signals danger to your nervous system. Releasing it signals safety, and safety precedes sleep.',
          'You have survived nights of poor sleep before and functioned the following day. Tomorrow may not be your best day, and that is genuinely okay. This is one night in a long story. It is manageable.',
          'The anxiety about not sleeping often keeps us more awake than the insomnia itself. If you can release the story about what not sleeping means, you release one of the main obstacles to sleep.',
          'There is nothing required of you right now except to breathe and to be still. Not to sleep perfectly, not to fix anything, not to plan the morning. Just this breath, this dark, this body at rest.',
          'Your nervous system responds to stillness and slow breathing even when the mind is active. Keep breathing slowly. Keep your body still. The system is working even if sleep feels far away.',
          'Whatever happens tonight, morning will come and with it a new opportunity. For now, give your body and mind the kindest conditions you can — stillness, slow breath, and the release of demands. That is enough.',
        ],
      },
    ],
  },

  // ── 6. Cuerpo ────────────────────────────────────────────────────────────────
  {
    id: 'cuerpo', label: 'Cuerpo', emoji: '🌿',
    themes: [
      {
        id: 'health-anxiety', label: 'Ansiedad por salud',
        phrases: [
          'Your body is deeply wise. It has overcome difficult things before and knows how to care for itself with the resources it has. Trust that innate intelligence.',
          'Health anxiety amplifies the normal signals of the body and turns them into threats. This breath calms the alarm system. You are changing the signal.',
          'Breathe deeply and consciously, bringing oxygen and calm to every part of your body. Feel that oxygen arriving even to the places where you feel tension.',
          'You do not need absolute certainty about everything to be well in this present moment. Certainty is not a condition for peace. Peace can exist with uncertainty.',
          'Excessive worry does not protect your health or prevent anything — but inner peace actively supports healing systems. You are choosing what works.',
          'With each breath, you activate the parasympathetic nervous system — the one that heals, regenerates, and rests. Not the one that alarms. You are using your body in favor of your well-being.',
          'Your body and you are completely on the same side. You are not adversaries — you are partners. Work with it, not against it, and you will notice the difference.',
          'Let go for a few minutes of the negative scenarios your mind generates. There is only this breath, this moment, this body functioning right now. Return to that.',
          'The catastrophizing mind is not objective reality — it is a modifiable thinking habit. Return to the present where your body, right now, is here and functioning.',
          'Be grateful for what your body does well today — every function, every movement, every sense. There is much if you look honestly. More than anxiety lets you see.',
          'You are doing the right thing by taking care of yourself and paying attention. Excessive worry does not help — this kind of conscious care genuinely does. Stay here.',
          'When you finish, carry a kinder, more collaborative, and less anxious relationship with your body. It is your ally. Treat it as such.',
        ],
      },
      {
        id: 'fatigue', label: 'Cansancio o agotamiento',
        phrases: [
          'Your body asked clearly for a pause and you listened to that signal. This session is exactly what you need right now. Well done for being here.',
          'You do not have to do anything else in this moment. Not produce, not solve, not respond to anything. Just breathe. That is all that is asked of you.',
          'The tiredness you feel is real, legitimate, and deserves to be acknowledged honestly. Do not minimize it or ignore it. It is a signal that you give a lot. Attend to it.',
          'With each deep breath, you bring renewing oxygen to every cell in your body that needs it. Feel that immediate relief moving through your tissues. Your body appreciates every breath.',
          'Rest is not giving up or failing. It is intelligently recharging to be able to continue better and farther. Athletes know this. Now you do too.',
          'Imagine that with each slow exhale, you expel the accumulated tiredness you carry in your body. With each inhale, you receive renewed energy. That real exchange is happening.',
          'Your body has an extraordinary capacity to recover when given adequate space. Give it that space now, without rush and without conditions. Watch how it responds.',
          'Not everything has to be done today and not everything can wait indefinitely. Learn to distinguish. Some things genuinely can wait for your renewed energy.',
          'Feel the real support of whatever is holding you physically right now. Release yourself completely into that surface. You do not have to hold your own weight right now.',
          'Rest is also deeply productive — the best creators, athletes, and thinkers know and practice this. It is not lost time. It is direct investment.',
          'You deserve to restore yourself completely. Not as an occasional luxury, but as a fundamental need of any human being who gives a lot. Claim that right now.',
          'When you finish, you will have a little more energy and clarity for what truly matters. Not everything, but something more. And that something more changes how the rest of the day looks.',
        ],
      },
      {
        id: 'pain', label: 'Dolor o tensión física',
        phrases: [
          'Your body speaks to you through pain and tension. Listen to it with gentleness and without resistance. That listening is already part of healing.',
          'Consciously bring your breath toward the specific place where you feel tension or discomfort. Imagine the air arriving directly to that area. Notice what happens.',
          'You do not have to fight against pain for it to diminish. Sometimes simply observing it calmly and without resistance transforms it. Try it with curiosity.',
          'With each deep inhale, you bring warmth, oxygen, and relief to that specific area of your body. Imagine a warm light expanding toward that place with each breath.',
          'Imagine your breath is a gentle, constant wave that softly massages that tension from within. Soft, without forcing. With each cycle, something yields a little.',
          'The nervous system and pain are deeply connected. What calms the nervous system reduces the perception of pain. This practice directly helps both.',
          'You are not your pain and you are not defined by it. You are the compassionate observer of that sensation. From that perspective you have more distance and more peace.',
          'With each conscious exhale, you release a small fraction of that accumulated tension. You do not have to release it all at once. Little by little, breath by breath.',
          'Your body deserves genuine care, gentle attention, and real kindness, not judgment or impatience. Treat it as you would treat someone who is suffering and needs compassion.',
          'This conscious pause is already real medicine for your nervous system and for the perception of pain. You are not waiting — you are acting. This counts.',
          'There are healing resources within you that are specifically activated by calm and deep breathing. You are accessing them right now. Trust that process.',
          'When you finish, you will carry a more compassionate, more patient, and kinder relationship with your body. That relationship directly affects how you experience pain. It is worth cultivating.',
        ],
      },
      {
        id: 'exercise', label: 'Antes o después del ejercicio',
        phrases: [
          'You are here to acknowledge and care for your body — the vehicle that carries everything you are and do. This moment is a gift you are giving it, whether before or after movement.',
          'If you are preparing to move — breathe and arrive fully in your body first. Feel it as an ally waiting to be used, not an obstacle to get through. This session sets the tone.',
          'Your body is extraordinary in its capacity to move, to adapt, and to grow stronger with consistent care. That capacity deserves to be honored, not taken for granted.',
          'Whether you are warming up or cooling down, your breath is the bridge between your mind and your physical self. Let it be the thread that connects them completely in this moment.',
          'Release any judgment about performance, appearance, or how today will compare to other days. This is about being present in your body right now, with what it can do today. That is enough.',
          'With each breath, bring awareness to the sensations in your body — not as problems to solve, but as information about a living system in motion. Curiosity, not judgment.',
          'If you just finished moving, honor the effort you gave. Every workout, however it felt, created adaptation. Your body is responding even now, rebuilding and becoming more capable.',
          'Rest is as important as effort in any physical practice. The growth happens during recovery, not only during exertion. This breath is part of the work, not separate from it.',
          'Think about why you move — not the aesthetic goals, but the deeper ones. Energy, mental clarity, longevity, how movement makes you feel from the inside. Connect with that real reason.',
          'Your body does not need to be perfect to deserve care and respect. Right now, in its current state, it deserves your attention, your gratitude, and your gentleness. Give it that.',
          'Every time you choose to move your body with intention, you are making a vote for your long-term health and your quality of life. That vote matters more than how any single session feels.',
          'When you leave here, carry that same presence into the movement or the recovery that follows. Breathe. Notice. Be in your body. That full presence makes everything more effective and more real.',
        ],
      },
      {
        id: 'body-scan', label: 'Escaneo corporal',
        phrases: [
          'This is a practice of coming home to your body — of bringing your full, unhurried attention to the physical self that carries you through every moment of your life. Begin here, with warmth and without judgment.',
          'Bring your attention to the top of your head. Notice whatever is there — warmth, pressure, tightness, or simply the feeling of existing. No need to change anything. Just arrive and observe.',
          'Now move your awareness slowly to your face. Your forehead, your jaw, the space behind your eyes. Allow these muscles to soften without effort. Just notice and breathe.',
          'Bring your attention to your neck and shoulders — the places where so many of us carry the weight of the day without realizing it. Breathe toward them and notice what happens when attention arrives.',
          'Move slowly to your chest and upper back. Feel your heart beating steadily. Feel your breath moving your ribs. Notice those automatic, faithful rhythms that support you without being asked.',
          'Bring awareness to your abdomen. Notice any tension, any holding, any sensation that has been waiting to be acknowledged. Breathe toward it gently and let it soften on its own.',
          'Move down to your hips and lower back — areas that often carry unacknowledged strain. Breathe toward them with the intention of releasing, not forcing. Just awareness and breath.',
          'Bring your attention to your legs — the thighs, the knees, the calves. These carry you through the world. Notice whatever is present there with the same quiet, non-judgmental attention.',
          'And finally, your feet. The foundation that connects you to the earth beneath you. Notice the sensations there — pressure, temperature, tingling. These extremities are still part of you, still worth attention.',
          'Now hold your entire body in awareness at once — all of it together, exactly as it is right now. Not as it was or as you wish it would be. As it is. This is your body today. It is enough.',
          'Your body communicates constantly. This practice teaches you to hear it before it has to shout. That listening relationship, developed with patience, is one of the most powerful forms of self-care there is.',
          'When you finish, carry a fragment of this bodily awareness into the next thing you do. Not a big meditation — just a small check-in. How does my body feel right now? That question, asked regularly, changes everything.',
        ],
      },
      {
        id: 'mindful-eating', label: 'Comida consciente',
        phrases: [
          'Before you eat, take this moment to arrive. To slow down from the pace of the day and become present to what you are about to receive. Your body will absorb not just food but the state you bring to it.',
          'Notice the experience of hunger in your body right now, if it is present. Where do you feel it? What does it actually feel like? This awareness connects you to a real and intelligent signal.',
          'Before the first bite, take a breath and look at what is in front of you. The colors, the textures, the smells. Food is sensory experience before it is fuel. Let yourself experience that.',
          'Eating slowly and with awareness allows your body\'s natural satiety signals to catch up with your intake. That feedback loop works — but only if you are present enough to hear it.',
          'This is a practice of respecting the nourishment your body needs. Not restricting, not overindulging from distraction — but genuinely listening to what is enough. That takes practice and gentleness.',
          'If you are eating to comfort an emotion, notice that without judgment. That is something your body learned to do for good reasons. Simply naming it with compassion is a meaningful act of awareness.',
          'The body does not differentiate between food eaten in stress and food eaten in calm — but the digestive system does. Calm enhances digestion, absorption, and satisfaction. This breath already helps.',
          'There are no bad foods and no good foods in this moment — just what you have chosen and your relationship with it. Bring curiosity to that relationship rather than judgment. What do you notice?',
          'Eating is one of the few moments in the day when you can practice full sensory presence. The taste, the texture, the temperature. Let each bite be complete before reaching for the next.',
          'Gratitude for food — for having it, for the hands that prepared it, for the process that brought it here — changes the quality of the experience. It is not sentiment. It is a real shift in awareness.',
          'You eat not just to fuel performance but to nourish a living being — yourself — who deserves that nourishment with care and presence. That reframe matters. You are worth feeding well.',
          'When you leave this practice, bring just a fraction of this presence to whatever you eat next. Not perfection — just one slow breath before the first bite. That is the whole practice, distilled.',
        ],
      },
    ],
  },
];

export const COMPLETION_QUOTES = [
  'Peace is not something you find outside. It is something you build within.',
  'Every time you stop to breathe consciously, you choose yourself.',
  'Meditating is not emptying the mind. It is learning to observe it with compassion.',
  'You are more than your thoughts. You are the space where thoughts occur.',
  'Stillness is not the absence of life. It is life at its fullest.',
  'Each conscious breath is an act of love toward yourself.',
  'It does not matter how long it lasted. What matters is that you chose it.',
  'When you care for yourself, you have more to give to others.',
  'The resting mind creates more than the mind that never stops.',
  'Today you proved that you can pause. That is a lot in a world that never stops.',
  'Well-being is not a destination. It is the direction in which you walk.',
  'Your breath will accompany you all your life. It is worth knowing it well.',
  'Just as you care for your body with exercise, you care for your mind with meditation.',
  'The calm you feel right now will always be available to you.',
  'You do not have to earn rest. You need it, and that is enough.',
  'In the silence you found something that noise cannot give you.',
  'Today you planted a seed of awareness. With time, it will grow.',
  'Each session makes you more skilled at returning to yourself.',
  'The path outward always begins inward.',
  'Your well-being is the foundation of everything else you build.',
];
